#!/usr/bin/env node
/*
 * _tools/build.mjs — ComponentX build engine
 * ---------------------------------------------------------------------
 * Regenerates CATALOG.md and MANIFEST.json from the components/ and
 * Designs/ trees. The same tool runs locally and in CI so the catalog
 * and the update manifest can never drift from the tree.
 *
 * Usage:
 *   node _tools/build.mjs             regenerate CATALOG.md + MANIFEST.json
 *   node _tools/build.mjs --bump      + bump the patch version when output changes
 *   node _tools/build.mjs --check     exit 1 when outputs are stale (CI smoke test)
 */

import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SKILL_DIR = path.join(ROOT, "skill");
const COMPONENTS_DIR = path.join(SKILL_DIR, "components");
const DESIGNS_DIR = path.join(SKILL_DIR, "Designs");
const PACKAGE_JSON = path.join(ROOT, "componentx.json");
const CATALOG_MD = path.join(SKILL_DIR, "CATALOG.md");
const MANIFEST_JSON = path.join(ROOT, "MANIFEST.json");

const FAMILY_FOCUS = {
  "3d": "3D, WebGL, and shader effects",
  animation: "motion, hover, and scroll effects",
  background: "gradients, beams, particles, and backdrops",
  button: "buttons, badges, and action triggers",
  card: "cards and content containers",
  "data-display": "tables, calendars, charts, and progress",
  feedback: "alerts, toasts, and validation states",
  form: "inputs, fields, and complete forms",
  layout: "grids, spacing, and page structure",
  loader: "spinners, skeletons, and loading states",
  media: "carousels, galleries, and media players",
  navigation: "navbars, menus, sidebars, and tabs",
  overlay: "modals, dialogs, popovers, and tooltips",
  text: "typography, text effects, and editors",
};

/*
 * Files that ship in a user install. Each entry is [repoPath, installPath]:
 * repoPath   — where the file lives in this repository (and its raw URL)
 * installPath — where it lands inside ~/.componentx (skill/ is flattened)
 * Everything else in the repo (installers, LICENSE, CHANGELOG, _tools, the
 * root README) is repo-side only and never touches a user's machine.
 */
const INSTALL_FILES = [
  ["skill/README.md", "README.md"],
  ["skill/SKILL.md", "SKILL.md"],
  ["skill/CATALOG.md", "CATALOG.md"],
  ["componentx.json", "componentx.json"],
  ["bin/componentx.mjs", "bin/componentx.mjs"],
  ["bin/componentx.cmd", "bin/componentx.cmd"],
  ["bin/componentx", "bin/componentx"],
];

/* ------------------------------------------------------------------ helpers */

async function readText(file) {
  return fs.existsSync(file) ? await fsp.readFile(file, "utf8") : "";
}

function titleCase(seed) {
  return seed
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (ch) => ch.toUpperCase())
    .trim();
}

/* Parse the YAML-ish frontmatter block that every ComponentX file carries. */
function parseFrontmatter(text) {
  if (!text.startsWith("---")) return {};
  const block = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!block) return {};
  const meta = {};
  for (const line of block[1].split(/\r?\n/)) {
    const hit = line.match(/^([A-Za-z_][A-Za-z_0-9]*):\s*(.+?)\s*$/);
    if (hit) meta[hit[1]] = hit[2].replace(/^"|"$/g, "").replace(/\\"/g, '"');
  }
  return meta;
}

function sha256(file) {
  const digest = crypto.createHash("sha256");
  digest.update(fs.readFileSync(file));
  return digest.digest().toString("hex");
}

function sha256Buffer(buf) {
  return crypto.createHash("sha256").update(buf).digest().toString("hex");
}

async function walkMd(dir) {
  if (!fs.existsSync(dir)) return [];
  const names = (await fsp.readdir(dir)).filter((n) => n.toLowerCase().endsWith(".md"));
  names.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
  return names;
}

function normalizeRelative(file) {
  return path.relative(ROOT, file).split(path.sep).join("/");
}

const CATALOG_BANNER =
  "<!-- ComponentX Catalog — generated by `node _tools/build.mjs`. Do not edit by hand. -->";

/* Keep `renderCatalog` and `buildManifest` separated so each stays readable. */
let catalogOut = "";
let manifestOut = "";

/* ------------------------------------------------------------- renderCatalog */

function renderCatalog(families, themes, counts) {
  const L = [];
  const totalComponents = counts.components;
  const totalThemes = counts.themes;

  L.push(CATALOG_BANNER);
  L.push("");
  L.push("# ⚡ ComponentX · Catalog");
  L.push("");
  L.push(`The complete ComponentX library — **${totalComponents} components** across **${families.length} semantic families** plus **${totalThemes} design themes**, every entry a deep link to its full file.`);
  L.push("");
  L.push("## How to use this catalog");
  L.push("");
  L.push("**Do not scan the whole library.** Classify the request, open the matching type folder, search filenames and tags, then read only the best 1–3 component files.");
  L.push("");
  L.push("```text");
  L.push("components/");
  const maxLen = Math.max(...families.map((f) => f.name.length));
  for (const f of families) {
    L.push("  " + "├── " + f.name.padEnd(maxLen) + "  " + String(f.files.length).padStart(3) + " components → " + f.focus);
  }
  L.push("Designs/");
  L.push("  " + "└── " + String(totalThemes).padStart(3) + " themes → premium UI style references");
  L.push("```");
  L.push("");
  L.push("### One-line install");
  L.push("");
  L.push("```bash");
  L.push("curl -fsSL https://raw.githubusercontent.com/naaafizz/ComponentX/main/install.sh | bash   # macOS / Linux");
  L.push("# PowerShell: irm https://raw.githubusercontent.com/naaafizz/ComponentX/main/install.ps1 | iex");
  L.push("# keep it fresh:  componentx update");
  L.push("```");
  L.push("");
  L.push("## Component families");
  L.push("");
  L.push("| Family | Components | Focus |");
  L.push("| :----- | :--------- | :---- |");
  for (const f of families) {
    L.push(`| [\`${f.name}/\`](#${f.name}) | ${f.files.length} | ${f.focus} |`);
  }
  L.push("");
  L.push("Every file carries `library: \"ComponentX\"` frontmatter and one of four quality tiers: `lightweight` · `standard` · `advanced` · `showcase`.");
  L.push("");
  L.push("## Recommended agent flow");
  L.push("");
  L.push("1. **Classify** — identify the component type.");
  L.push("2. **Search** — filter that folder by filename/tags.");
  L.push("3. **Shortlist** — pick 1–3 candidates.");
  L.push("4. **Read** — open only those files.");
  L.push("5. **Adapt** — check quality, dependencies, and implementation details, then implement.");
  L.push("");
  L.push("## Naming");
  L.push("");
  L.push("Filenames are normalized and carry no source-library branding suffixes. Numeric suffixes (`-2`, `-3`) exist only for normalized-name collisions.");
  L.push("");
  for (const f of families) {
    L.push("---");
    L.push("");
    L.push(`## \`${f.name}/\` · ${f.files.length} component${f.files.length === 1 ? "" : "s"}`);
    L.push("");
    L.push(`_${f.focus}._`);
    L.push("");
    for (const c of f.files) {
      L.push(`- [**${c.name}**](components/${f.name}/${c.file}) — \`${c.quality}\``);
    }
    L.push("");
  }
  L.push("---");
  L.push("");
  L.push("## 🎨 Design themes");
  L.push("");
  L.push(`The **${totalThemes} themes** in the \`Designs/\` folder are complete visual languages — apply one when a request asks for a specific brand feel (\`make it look like Linear\`), a dark/light mood, or a premium style system.`);
  L.push("");
  L.push("| Theme | Mode | Focus |");
  L.push("| :---- | :--- | :---- |");
  for (const t of themes) {
    L.push(`| [**${t.name}**](Designs/${t.file}) | ${t.mode} | ${t.focus} |`);
  }
  L.push("");
  L.push("### Theme routing");
  L.push("");
  L.push("1. Match the requested brand or mood to a theme file name.");
  L.push("2. Open only that file.");
  L.push("3. Port the CSS tokens (colors, type, spacing, radius, shadows) into the host project's design system.");
  L.push("");
  L.push("---");
  L.push("");
  L.push("[⬆ Back to top](#-componentx--catalog) · **ComponentX** — semantic, token-efficient components");
  L.push("");

  return L.join("\n");
}

/* -------------------------------------------------------------- scanDesigns */

async function scanDesigns() {
  const files = await walkMd(DESIGNS_DIR);
  const themes = [];
  for (const file of files) {
    const text = await readText(path.join(DESIGNS_DIR, file));
    const modeHit = text.match(/\*\*Theme:\*\*\s*(\w+)/);
    const heading = text.match(/^#\s+(.+)$/m);
    // First meaningful paragraph — the one-line "style thesis".
    const focusHit = text
      .split(/\r?\n/)
      .map((l) => l.trim())
      .find((l) => l.length > 40 && !l.startsWith("#") && !l.startsWith(">") && !l.startsWith("**Theme:"));
    let name = heading ? heading[1].trim() : file.replace(/\.md$/i, "");
    name = name.replace(/\s*[-–—]\s*Style Reference\s*$/i, "").replace(/\s*[-–—]\s*.*$/i, "").trim();
    themes.push({
      file,
      name: name || titleCase(file.replace(/\.md$/i, "")),
      mode: modeHit ? modeHit[1].toLowerCase() : "",
      focus: focusHit ? focusHit.slice(0, 140) + (focusHit.length > 140 ? "…" : "") : "",
    });
  }
  themes.sort((a, b) => a.file.localeCompare(b.file));
  return themes;
}

/* ----------------------------------------------------------- scanComponents */

async function scanComponents() {
  const families = [];
  for (const dir of await fsp.readdir(COMPONENTS_DIR)) {
    const abs = path.join(COMPONENTS_DIR, dir);
    if (!fs.statSync(abs).isDirectory()) continue;
    const focus = FAMILY_FOCUS[dir] || "components";
    const files = [];
    for (const file of await walkMd(abs)) {
      const meta = parseFrontmatter(await readText(path.join(abs, file)));
      const stem = file.replace(/\.md$/i, "");
      files.push({
        file,
        name: meta.name || titleCase(stem),
        quality: meta.quality || "standard",
      });
    }
    files.sort((a, b) => a.file.localeCompare(b.file, undefined, { sensitivity: "base" }));
    families.push({ name: dir, focus, files });
  }
  families.sort((a, b) => a.name.localeCompare(b.name));
  return families;
}

/* ------------------------------------------------------------ buildManifest */

async function collectManifestFiles(catalogSha, catalogSize) {
  const entries = [];
  const installPath = (repoRel) => (repoRel.startsWith("skill/") ? repoRel.slice("skill/".length) : repoRel);
  for (const [repoPath, installRel] of INSTALL_FILES) {
    const abs = path.join(ROOT, ...repoPath.split("/"));
    if (repoPath === "skill/CATALOG.md") {
      // hash the freshly-rendered catalog, never the stale file on disk
      entries.push({ path: repoPath, install: installRel, size: catalogSize, sha256: catalogSha });
    } else if (fs.existsSync(abs)) {
      entries.push({ path: repoPath, install: installRel, size: fs.statSync(abs).size, sha256: sha256(abs) });
    }
  }
  for (const family of await fsp.readdir(COMPONENTS_DIR)) {
    const abs = path.join(COMPONENTS_DIR, family);
    if (!fs.statSync(abs).isDirectory()) continue;
    for (const file of await walkMd(abs)) {
      const fileAbs = path.join(abs, file);
      entries.push({
        path: normalizeRelative(fileAbs),
        install: installPath(normalizeRelative(fileAbs)),
        size: fs.statSync(fileAbs).size,
        sha256: sha256(fileAbs),
      });
    }
  }
  for (const file of await walkMd(DESIGNS_DIR)) {
    const fileAbs = path.join(DESIGNS_DIR, file);
    entries.push({
      path: normalizeRelative(fileAbs),
      install: installPath(normalizeRelative(fileAbs)),
      size: fs.statSync(fileAbs).size,
      sha256: sha256(fileAbs),
    });
  }
  entries.sort((a, b) => (a.path < b.path ? -1 : 1));
  return entries;
}

/* ------------------------------------------------------------------- main */

const args = process.argv.slice(1);
const doBump = args.includes("--bump");
const doCheck = args.includes("--check");

async function main() {
  const pkg = JSON.parse(await readText(PACKAGE_JSON));
  const families = await scanComponents();
  const themes = await scanDesigns();
  const counts = {
    components: families.reduce((n, f) => n + f.files.length, 0),
    themes: themes.length,
  };

  const catalog = renderCatalog(families, themes, counts);
  // Hash the freshly-rendered catalog in memory — never the stale file on disk.
  const catalogBytes = Buffer.from(catalog, "utf8");
  const files = await collectManifestFiles(sha256Buffer(catalogBytes), catalogBytes.length);
  const manifest = {
    schema: "1.0",
    name: pkg.name,
    version: pkg.version,
    repository: pkg.repository,
    defaultBranch: pkg.defaultBranch,
    generatedAt: new Date().toISOString().replace(/\.\d+Z$/, "Z"),
    counts: {
      components: counts.components,
      families: families.length,
      themes: counts.themes,
      files: files.length,
    },
    families: Object.fromEntries(families.map((f) => [f.name, f.files.length])),
    files,
  };

  // For drift detection, normalize the timestamp so two consecutive builds of
  // an unchanged tree always compare equal (generatedAt differs every run).
  const comparable = JSON.stringify({ ...manifest, generatedAt: "<ts>" }, null, 2);
  let prevNormalized = null;
  try {
    const prevParsed = JSON.parse(await readText(MANIFEST_JSON));
    prevNormalized = JSON.stringify({ ...prevParsed, generatedAt: "<ts>" }, null, 2);
  } catch {
    prevNormalized = null;
  }
  const changed = catalog !== (await readText(CATALOG_MD)) || comparable !== prevNormalized;

  if (doCheck) {
    // --check is a read-only guard: exit non-zero if a rebuild WOULD change
    // on-disk output (i.e. the committed catalog/manifest are stale).
    process.exit(changed ? 1 : 0);
  }

  if (changed && doBump) {
    const [major, minor, patch] = pkg.version.split(".").map(Number);
    pkg.version = `${major}.${minor}.${patch + 1}`;
    manifest.version = pkg.version;
    await fsp.writeFile(PACKAGE_JSON, JSON.stringify(pkg, null, 2) + "\n", "utf8");
    changed = true;
  }
  await fsp.writeFile(CATALOG_MD, catalog, "utf8");
  await fsp.writeFile(MANIFEST_JSON, JSON.stringify(manifest, null, 2) + "\n", "utf8");

  const action = doBump && changed ? "bumped →" : "";
  console.log(`componentx build  ·  ${action} catalog ${families.length} families / ${counts.components} components · ${counts.themes} themes · ${files.length} files tracked · v${manifest.version}`);
  process.exit(0);
}

await main();